[package]
name = "move-unit-test"
version = "0.1.0"
authors = ["Diem Association <opensource@diem.com>"]
description = "Unit testing framework for Move"
repository = "https://github.com/diem/diem"
homepage = "https://diem.com"
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
anyhow = "1.0.52"
structopt = "0.3.21"
colored = "2.0.0"
rayon = "1.5.0"

regex = "1.1.9"

move-command-line-common = { path = "../../move-command-line-common" }
move-stdlib = { path = "../../move-stdlib", features = ["testing"] }
move-core-types = { path = "../../move-core/types" }
move-compiler = { path = "../../move-compiler" }
move-vm-types = { path = "../../move-vm/types" }
move-vm-runtime = { path = "../../move-vm/runtime", features = ["testing"] }
move-vm-test-utils = { path = "../../move-vm/test-utils" }
move-resource-viewer = { path = "../move-resource-viewer" }
move-binary-format = { path = "../../move-binary-format" }
move-model = { path = "../../move-model" }
move-stackless-bytecode-interpreter = { path = "../../move-prover/interpreter" }
move-bytecode-utils = { path = "../move-bytecode-utils" }
workspace-hack = { version = "0.1", path = "../../../crates/workspace-hack" }

[dev-dependencies]
datatest-stable = "0.1.1"
difference = "2.0.0"

[[bin]]
name = "move-unit-test"
path = "src/main.rs"

[[test]]
name = "move_unit_test_testsuite"
harness = false
