[package]
name = "move-package"
version = "0.1.0"
authors = ["Diem Association <opensource@diem.com>"]
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
toml = "0.5.8"
serde = { version = "1.0", features = ["derive"] }
petgraph = "0.5.1"
anyhow = "1.0.52"
walkdir = "2.3.1"
clap = { version = "3.1", features = ["derive"] }
bcs = "0.1.2"
colored = "2.0.0"
serde_yaml = "0.8.17"
tempfile = "3.2.0"
sha2 = "0.9.3"
regex = "1.1.9"
ptree = "0.4.0"
once_cell = "1.7.2"
named-lock = "0.1.1"

move-binary-format = { path = "../../move-binary-format" }
move-compiler = { path = "../../move-compiler" }
move-bytecode-source-map = { path = "../../move-ir-compiler/move-bytecode-source-map" }
move-abigen = { path = "../../move-prover/move-abigen" }
move-docgen = { path = "../../move-prover/move-docgen" }
move-errmapgen = { path = "../../move-prover/move-errmapgen" }
move-core-types = { path = "../../move-core/types" }
move-symbol-pool = { path = "../../move-symbol-pool" }
move-command-line-common = { path = "../../move-command-line-common" }
move-model = { path = "../../move-model" }
move-bytecode-utils = { path = "../move-bytecode-utils" }
workspace-hack = { version = "0.1", path = "../../../crates/workspace-hack" }

[dev-dependencies]
datatest-stable = "0.1.1"

[[test]]
name = "test_runner"
harness = false
